name: Remote Dispatch Action
on: [repository_dispatch]
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' payload '${{ github.event.client_payload.tag }}'"
          echo  "commit hash '${{ github.event.client_payload.sha }}'"
      - uses: actions/checkout@v2.1.1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Run update script
        run:  ./.github/workflows/update-gardenctl.sh ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.sha }}
      - name: Commit files
        run: |
          git config --local user.email "gardener.ci.user2@gmail.com"
          git config --local user.name "gardener-ci2"
          git commit -m "Update gardenctl" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}